services:
  # Langfuse Database
  langfuse-db:
    image: postgres:16-alpine
    container_name: langfuse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: langfuse
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse_password_change_me  # CHANGEME
    volumes:
      - langfuse-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"  # Using 5435 to avoid conflicts with other PostgreSQL instances
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Langfuse ClickHouse (for analytics)
  langfuse-clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: langfuse-clickhouse
    restart: unless-stopped
    platform: linux/amd64
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: langfuse
      CLICKHOUSE_USER: langfuse
      CLICKHOUSE_PASSWORD: clickhouse_password_change_me  # CHANGEME
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - langfuse-clickhouse-data:/var/lib/clickhouse
    ports:
      - "8125:8123"  # Using 8125 to avoid conflicts
      - "9002:9000"  # Using 9002 to avoid conflicts
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  langfuse-redis:
    image: redis:7-alpine
    container_name: langfuse-redis
    restart: unless-stopped
    volumes:
      - langfuse-redis-data:/data
    ports:
      - "6380:6379"  # Using 6380 to avoid conflicts
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Langfuse Web Application
  langfuse-web:
    image: langfuse/langfuse:2
    container_name: langfuse-web
    restart: unless-stopped
    depends_on:
      langfuse-db:
        condition: service_healthy
      # langfuse-clickhouse:
      #   condition: service_healthy
      langfuse-redis:
        condition: service_healthy
    ports:
      - "3200:3000"  # Using 3200 to avoid conflicts with other apps
    environment:
      # Database
      DATABASE_URL: postgresql://langfuse:langfuse_password_change_me@langfuse-db:5432/langfuse  # CHANGEME

      # ClickHouse (disabled for macOS compatibility)
      # CLICKHOUSE_URL: http://langfuse-clickhouse:8123
      # CLICKHOUSE_USER: langfuse
      # CLICKHOUSE_PASSWORD: clickhouse_password_change_me  # CHANGEME

      # Redis
      REDIS_HOST: langfuse-redis
      REDIS_PORT: 6379
      REDIS_AUTH: ""

      # Application
      NEXTAUTH_URL: http://localhost:3200
      NEXTAUTH_SECRET: your_nextauth_secret_change_me_min_32_chars  # CHANGEME - minimum 32 characters
      SALT: your_salt_change_me_min_32_characters_long  # CHANGEME - minimum 32 characters

      # Optional: Telemetry (set to true to enable)
      TELEMETRY_ENABLED: "false"

      # Optional: Configure auth providers
      # AUTH_DISABLE_USERNAME_PASSWORD: false

      # Optional: Email configuration for user invites
      # EMAIL_FROM_ADDRESS: noreply@yourdomain.com
      # SMTP_CONNECTION_URL: smtp://username:password@smtp.example.com:587

  # Langfuse Worker (for async processing)
  langfuse-worker:
    image: langfuse/langfuse:2
    container_name: langfuse-worker
    restart: unless-stopped
    depends_on:
      langfuse-db:
        condition: service_healthy
      # langfuse-clickhouse:
      #   condition: service_healthy
      langfuse-redis:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: postgresql://langfuse:langfuse_password_change_me@langfuse-db:5432/langfuse  # CHANGEME

      # ClickHouse (disabled for macOS compatibility)
      # CLICKHOUSE_URL: http://langfuse-clickhouse:8123
      # CLICKHOUSE_USER: langfuse
      # CLICKHOUSE_PASSWORD: clickhouse_password_change_me  # CHANGEME

      # Redis
      REDIS_HOST: langfuse-redis
      REDIS_PORT: 6379
      REDIS_AUTH: ""

      # Application
      NEXTAUTH_URL: http://localhost:3200
      NEXTAUTH_SECRET: your_nextauth_secret_change_me_min_32_chars  # CHANGEME
      SALT: your_salt_change_me_min_32_characters_long  # CHANGEME
    command: worker

volumes:
  langfuse-db-data:
    driver: local
  langfuse-clickhouse-data:
    driver: local
  langfuse-redis-data:
    driver: local
